HUGCHAT Tool
Aggregate-Intellect/sherpa pull request #246
Opened 2023-12-01 05:12 UTC by Aminolroaya

2023-12-08 05:32 UTC, 20001LastOrder commented
Thanks for the PR. could you provide a bit more information (maybe a link) about how I can find the environment variables for hugging face and test it locally?

2023-12-08 05:33 UTC, 20001LastOrder commented
Nevermind, I realized it's just the password and email...

2023-12-08 05:41 UTC, 20001LastOrder requested changes
Thanks for the PR. Just some minor comments, please see them below.

2023-12-08 05:41 UTC, 20001LastOrder commented on src/tests/unit_tests/tools/test_hug_chat_tool.py
> +from sherpa_ai.tools import HugChatTool
Please add a new line at the end and add `@external_api` before the test

2023-12-08 05:41 UTC, 20001LastOrder commented on src/sherpa_ai/tools.py
> +        cookie_path_dir = "./cookies_snapshot"
I think even if we cannot avoid the cookies, we don't need to save them locally. We can remove line 236 and 237

2023-12-12 03:42 UTC, oshoma commented
Hi @Aminolroaya @20001LastOrder  I made some changes as follows:

- enable offline testing with omcks
- enable online testing 
- reformat 
- get Poetry in synch with `main` 

Could you both please try running the following tests to be sure everything works and report back here? If you have Hugging Chat credentials in your .env file then you should get 11 passing tests. Without credentials you should get 10 passing tests and 1 skipped test.

```
poetry install
pytest tests/unit_tests/tools/test_hug_chat_tool.py   -v
```

And if that works, try `pytest tests` too. Here's my output: `1 failed, 56 passed, 2 skipped, 13 warnings`. 
The failure is expected, it will be resolved when we fix #252.

@20001LastOrder If tests run clean and your code review is OK then I think with these changes we are ready to merge into `main`. We should do a squash merge.

2024-02-02 21:25 UTC, Aminolroaya commented
@oshoma apologies for the late reply. Is there anything that needs to be taken care of before merging? cc @amirfz

2024-02-02 22:27 UTC, amirfz commented
@Aminolroaya I think there are some unaddressed comments from Osh on this PR. have you seen those?

2024-02-03 14:46 UTC, Aminolroaya commented
> @Aminolroaya I think there are some unaddressed comments from Osh on this PR. have you seen those?

Yes. Just want to check if using the Hugchat tool is still considered an enhancement for the project. If yes, I will look into it this weekend. tnx.

2024-02-07 17:45 UTC, 20001LastOrder commented
@Aminolroaya I think this is definitely still valuable. Especially now we are planning on fully configurable agents, adding a new tool to an agent will be much easier. Thus, an additional tool would be nice for different use cases.

2024-11-20 21:05 UTC, 20001LastOrder commented
Closed as not planned

2024-11-20 21:05 UTC, closed without merging