Set QA Agent as the default agent in SlackApp and add configuration for the obsolete agent
Aggregate-Intellect/sherpa pull request #270
Opened 2023-12-19 20:31 UTC by 20001LastOrder

# Description
Resolves #261 

Now the QA agent will be used as the default agent. The `--obsolete` flag can be used to switch back to the old task agent. 

# Your checklist for this pull request
Thank you for submitting a pull request! To speed up the review process, please follow this checklist:

- [x] My Pull Request is small and focused on one topic so it can be reviewed easily 
- [x] My code follows the style guidelines of this project (`make format`)
- [x] Commit messages are detailed
- [x] I have performed a self-review of my code
- [x] I commented hard-to-understand parts of my code
- [x] I updated the documentation (docstrings, `/docs`)
- [x] My changes generate no new warnings (or explain any new warnings and why they're ok)
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] All tests pass when I run `pytest tests` (offline mode)

Additional steps for code with networking dependencies (Does not apply):

- [ ] I followed the [offline and online testing guidelines](https://sherpa-ai.readthedocs.io/en/latest/How_To/Test/test.html#offline-and-online-testing)
- [ ] All tests pass when I run `pytest tests --external_api` (online mode, making network calls)

2024-01-08 23:56 UTC, oshoma commented
Hey @20001LastOrder when I don't have Pinecone keys defined in `.env` I get this test failure. Can you resolve?

```python
_______________________________________________________________________________________________ test_extract_github_readme_with_valid_url_succeeds _______________________________________________________________________________________________

    def test_extract_github_readme_with_valid_url_succeeds():
        repo_url = "https://github.com/Aggregate-Intellect/sherpa"
>       content = extract_github_readme(repo_url)

tests/unit_tests/scrape/test_extract_github_readme.py:6: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
sherpa_ai/scrape/extract_github_readme.py:58: in extract_github_readme
    save_to_pine_cone(content, metadata)
sherpa_ai/scrape/extract_github_readme.py:69: in save_to_pine_cone
    vectorstore = ConversationStore("Github_data", index, embeddings, "text")
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <sherpa_ai.connectors.vectorstores.ConversationStore object at 0x7fa9ddf25100>, namespace = 'Github_data', db = <pinecone.index.Index object at 0x7fa9daa59b20>
embeddings = OpenAIEmbeddings(client=<class 'openai.api_resources.embedding.Embedding'>, async_client=None, model='text-embedding-a...show_progress_bar=False, model_kwargs={}, skip_empty=False, default_headers=None, default_query=None, http_client=None)
text_key = 'text'

    def __init__(self, namespace, db, embeddings, text_key):
        self.db = db
        self.namespace = namespace
>       self.embeddings = embeddings
E       AttributeError: can't set attribute

sherpa_ai/connectors/vectorstores.py:24: AttributeError
```

2024-01-09 00:44 UTC, oshoma commented
Re:   AttributeError: can't set attribute

This bug still occurs when I have pinecone set up. Maybe you're using a different langchain version?

```
(base) ➜  src git:(slackapp) ✗ poetry show langchain
 name         : langchain                                             
 version      : 0.0.332                                               
 description  : Building applications with LLMs through composability 

dependencies
 - aiohttp >=3.8.3,<4.0.0
 - anyio <4.0
 - async-timeout >=4.0.0,<5.0.0
 - dataclasses-json >=0.5.7,<0.7
 - jsonpatch >=1.33,<2.0
 - langsmith >=0.0.52,<0.1.0
 - numpy >=1,<2
 - pydantic >=1,<3
 - PyYAML >=5.3
 - requests >=2,<3
 - SQLAlchemy >=1.4,<3
 - tenacity >=8.1.0,<9.0.0
```

Hmm... I also see the test will probably fail if I don't set up Pinecone with an index named "langchain".

We should change the test so that it's more robust
- skipped when Pinecone is not set up 
- skipped when OpenAI key is not set
- make this an external API test with mocks?

2024-01-09 00:55 UTC, oshoma requested changes
Suggesting some aesthetic changes here and maybe adding a test or two.

See also the bug I ran into... I haven't been able to get that broken test to succeed. Not sure whether it's related.

2024-01-09 00:55 UTC, oshoma commented on src/apps/slackapp/tests/test_switch_agents.py
> +def test_normal_mode(mock_task_agent_run, mock_qa_agent_run):
test_normal_mode_uses_qa_agent

2024-01-09 00:55 UTC, oshoma commented on src/apps/slackapp/tests/test_switch_agents.py
> +def test_obsolete_mode(mock_task_agent_run, mock_qa_agent_run):
test_obsolete_mode_uses_task_agent

2024-01-09 00:55 UTC, oshoma commented on src/sherpa_ai/config/task_config.py
> +            help="enable performing the obsolete step for each agent.",
hmm... maybe "enable use of task agent (obsolete)"

2024-01-09 00:55 UTC, oshoma commented on src/sherpa_ai/output_parsers/link_parse.py
> +            if doc_id <= 0 or doc_id > len(self.links):
If you fixed a bug here then add a test

2024-01-09 00:55 UTC, oshoma commented on src/apps/slackapp/slackapp/bolt_app.py
> +        verbose_logger.log("⚠️🤖 Use obsolete mode ...")
Use task agent (obsolete)...

2024-01-09 00:55 UTC, oshoma commented on src/sherpa_ai/config/task_config.py
> +    obsolete: bool = False
General comment: for anyone who hasn't seen this code before, "obsolete" is too vague.  I suggest calling it something like `use_task_agent`, and in the parser.add_argument and/or elsewhere in the docs you can explain this mode of operation is obsolete.

2024-01-09 21:15 UTC, 20001LastOrder commented
> Re: AttributeError: can't set attribute
> 
> This bug still occurs when I have pinecone set up. Maybe you're using a different langchain version?
> 
> ```
> (base) ➜  src git:(slackapp) ✗ poetry show langchain
>  name         : langchain                                             
>  version      : 0.0.332                                               
>  description  : Building applications with LLMs through composability 
> 
> dependencies
>  - aiohttp >=3.8.3,<4.0.0
>  - anyio <4.0
>  - async-timeout >=4.0.0,<5.0.0
>  - dataclasses-json >=0.5.7,<0.7
>  - jsonpatch >=1.33,<2.0
>  - langsmith >=0.0.52,<0.1.0
>  - numpy >=1,<2
>  - pydantic >=1,<3
>  - PyYAML >=5.3
>  - requests >=2,<3
>  - SQLAlchemy >=1.4,<3
>  - tenacity >=8.1.0,<9.0.0
> ```
> 
> Hmm... I also see the test will probably fail if I don't set up Pinecone with an index named "langchain".
> 
> We should change the test so that it's more robust
> 
> * skipped when Pinecone is not set up
> * skipped when OpenAI key is not set
> * make this an external API test with mocks?

We are aware of this bug, see this issue: #256

2024-01-10 21:40 UTC, oshoma approved these changes

2024-01-10 21:40 UTC, merged