entity validation =
Aggregate-Intellect/sherpa pull request #298
Opened 2024-02-19 02:44 UTC by Eyobyb

# Your checklist for this pull request
Thank you for submitting a pull request! To speed up the review process, please follow this checklist:

- [ ] My Pull Request is small and focused on one topic so it can be reviewed easily 
- [x] My code follows the style guidelines of this project (`make format`)
- [ ] Commit messages are detailed
- [x] I have performed a self-review of my code
- [x] I commented hard-to-understand parts of my code
- [x] I updated the documentation (docstrings, `/docs`)
- [ ] My changes generate no new warnings (or explain any new warnings and why they're ok)
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] All tests pass when I run `pytest tests` (offline mode)

Additional steps for code with networking dependencies:

- [ ] I followed the [offline and online testing guidelines](https://sherpa-ai.readthedocs.io/en/latest/How_To/Test/test.html#offline-and-online-testing)
- [ ] All tests pass when I run `pytest tests --external_api` (online mode, making network calls)

This is entity validation, designed to check if entities from the context exist in the answer. If they do not, the system will reprompt to add those entities. There are three stages of entity validation: first, string comparison from the list of entities extracted using spaCy; second, using metrics; and third, utilizing language model (LLM)

pervious pr #295 
issue  #274

2024-02-19 23:52 UTC, oshoma requested changes
@Eyobyb and @20001LastOrder please coordinate with each other on this Entity Validation PR (#298) and the Hydra Config PR #289. 

PR #289 contains changes to number validation and configuration settings like TEMPERATURE. Those changes need to be be picked up and carried forward in this PR as well. 

There are two options:
1. Merge Entity Validation #298 into main first, then rebase Hydra Config #298 on main (or on #298).
2. Merge Hydra Config into main first, then rebase Entity Validation on main (or on Hydra Config).

2024-02-20 00:35 UTC, oshoma requested changes

2024-02-20 00:35 UTC, oshoma commented on src/tests/unit_tests/test_util.py
> +    print(result["messages"])
please remove all the print() statements throughout this PR

2024-02-20 00:35 UTC, oshoma commented on src/tests/unit_tests/test_util.py
> +def test_extract_entities_without_entities():
also test extract_entities with None and a blank string ""

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +def json_extractor(text):
json_extractor => json_from_text

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +        I have a question and an answer. I want you to confirm if the entities from the question has been in some form inside the answer.
I have a question and an answer. I want you to confirm whether the entities from the question are mentioned in some form within the answer.

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +           only return { entity_exist: 'true' , messages:"" } if entities are mentioned inside the answer in
remove "in" from end of line 445, I think?

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +           only return {entity_exist: 'false' , messages: " Entity x hasn't been mentioned inside the answer"} if the entity is not mentioned properly .
only return {entity_exist: 'false' , messages: " Entity x is not mentioned within the answer"} if the entity is not mentioned within the answer .

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +def text_similarity_by_metrics(check_entity: List[str], source_entity: List[str]):
check_entity => check_entities
source_entity => source_entities

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +        for sub_entitiy in check_entity:
sub_entitiy => sub_entity

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +        - levenshtein_constant (float): Weight for the Levenshtein distance in the combined metric.
levenshtein_constant  => levenshtein_weight 

levenshtein_weight (float):  Weight between 0 and 1.0 for the Levenshtein distance in the combined metric.

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +            if metrics_value < combined_similarity:
metrics_value = max(combined_similarity, metrics_value)

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +    threshold = 0.75
threshold => probably_mentioned

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +        for entity in error_entity:
entities = ", ".join(error_entity)
message = f"remember to address these entities {entities} in final the answer."

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +def text_similarity(check_entity: List[str], source_entity: List[str]):
check_entity => check_entities
source_entity => source_entities

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +    for entity in source_entity:
use Python set difference instead of a for loop

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +            message += entity + ", "
message += ", ".join(error_entity)

2024-02-20 00:35 UTC, oshoma commented on src/sherpa_ai/utils.py
> +    check_entity = extract_entities(result)
Let's rework this `stage` variable. You are implementing a state machine here. So give the states meaningful names, e.g. TEXT_SIMILARITY_BASIC = 0, TEXT_SIMILARITY_BY_METRICS = 1, TEXT_SIMILARITY_BY_LLM = 2. Something like that. 

If function callers must know what these states mean then define them at the top of this file so they are obvious. 

Alternatively, is there a way to hide all of this from function callers? It seems like implementation detail to me, but I haven't been part of the design conversation.

2024-02-20 00:35 UTC, oshoma commented on src/tests/integration_tests/test_entity_citation_validator.py
> +@pytest.mark.parametrize(
Hooray for parametrize! 🥇

2024-02-20 00:35 UTC, oshoma commented on src/tests/integration_tests/test_entity_citation_validator.py
> +            match_found = any( 1 - jaccard_distance(set_a, result_entity.split()) >= 0.7 for result_entity in result_entities)
here you are using 0.7, and elsewhere in the code there is a 0.75 value. are they meant to be the same? if so, define a constant and use it (import it) in the test.

2024-02-20 00:35 UTC, oshoma commented on src/tests/unit_tests/test_util.py
> +def test_json_extractor_valid_json():
nice tests.
these tests could also be made more concise with parametrize.

remember to check the failure cases and corner cases like `None` and `""`

2024-02-21 12:40 UTC, Eyobyb commented on src/sherpa_ai/utils.py
> +def check_entities_match(result: str, source: str, stage: int):
we talked about it and decided to move this to the Hydra Config after merging it

2024-02-22 16:51 UTC, oshoma commented
> @Eyobyb and @20001LastOrder please coordinate with each other on this Entity Validation PR (#298) and the Hydra Config PR #289. PR #289 contains changes to number validation and configuration settings like TEMPERATURE. Those changes need to be be picked up and carried forward in this PR as well.
> 
> There are two options:
> 
> 1. Merge Entity Validation [Entity validation #298](https://github.com/Aggregate-Intellect/sherpa/pull/298) into main first, then rebase Hydra Config [Entity validation #298](https://github.com/Aggregate-Intellect/sherpa/pull/298) on main (or on [Entity validation #298](https://github.com/Aggregate-Intellect/sherpa/pull/298)).
> 2. Merge Hydra Config into main first, then rebase Entity Validation on main (or on Hydra Config).

Noting that Hydra Config PR #289 is now merged into main. @Eyobyb please rebase your Entity Validation work on main.

2024-02-29 13:54 UTC, closed without merging