Added blueprint arugment
Aggregate-Intellect/sherpa pull request #389
Opened 2024-06-04 05:04 UTC by andytai7

# Description
Added blueprint argument so that if blueprint already exists, this step is skipped. 

> Add directions for contributors. For example, do developers need to run `poetry install` after picking up these changes?

# Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Maintenance
- [ ] New release

# Related issues
> Mention related GitHub and Linear issues. E.g. Closes #xxx or Fixes #xxx. Otherwise delete this section.

# Checklists
To speed up the review process, please follow these checklists:

## Development
- [X] The Pull Request is small and focused on one topic
- [ ] Lint rules pass locally (`make format && make lint`)
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development (`make test`)
- [ ] The changes generate no new warnings (or explain any new warnings and why they're ok)
- [X] Commit messages are detailed
- [ ] Changed code is self-explanatory and/or I added comments
- [ ] I updated the documentation (docstrings, /docs)
See the testing guidelines for help on tests, especially those involving web services.

## Code review
- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ] I have performed a self-review of my code
- [ ] Issue from task tracker has a link to this pull request

💔 Thank you for submitting a pull request!

2024-06-04 12:36 UTC, amirfz requested changes
@andytai7 could you please also update the tutorial with this information? I'm esp interested in this: if I want to provide an external blueprint, what format does it have to have? it might even be best to include a template for it that I can download, modify, and use.

2024-06-07 17:23 UTC, amirfz commented
@20001LastOrder looks good to me. could you review and merge if it looks good?

2024-06-11 04:45 UTC, 20001LastOrder commented on demo/blog_writer/main.py
> +    parser.add_argument("--blueprint", type=str, help="Optional JSON blueprint file to use")
By default, arguments in `add_argument` are required. You will need to add a default value such as `default=None` to make it optional I think.

2024-06-11 04:47 UTC, 20001LastOrder commented on demo/blog_writer/main.py
> +    parser.add_argument("--blueprint", type=str, help="Optional JSON blueprint file to use")
Nevermind, I think this is no longer the case.

2024-06-11 04:47 UTC, 20001LastOrder commented
@amirfz This looks good to me. But you will need to approve it before I can merge (since you asked for some changes before)

2024-06-11 12:48 UTC, amirfz approved these changes

2024-06-11 12:48 UTC, merged