Feature/link scraper as an action
Aggregate-Intellect/sherpa pull request #430
Opened 2024-10-07 11:59 UTC by Eyobyb

# Description
- Add a link scraper action which will scrape and summarize with at most 3000 tokens of result. 
- Add a test for the link scraper actions 
# Type of change
- [ ] Bug fix (non-breaking change that fixes an issue)
- [x] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Maintenance
- [ ] New release

# Related issues
> Mention related GitHub and Linear issues. E.g. Closes #xxx or Fixes #xxx. Otherwise delete this section.

# Checklists
To speed up the review process, please follow these checklists:

## Development
- [x] The Pull Request is small and focused on one topic
- [x] Lint rules pass locally (`make format && make lint`)
- [ ] The code changed/added as part of this pull request has been covered with tests
- [ ] All tests related to the changed code pass in development (`make test`)
- [ ] The changes generate no new warnings (or explain any new warnings and why they're ok)
- [x] Commit messages are detailed
- [ ] Changed code is self-explanatory and/or I added comments
- [ ] I updated the documentation (docstrings, /docs)
See the testing guidelines for help on tests, especially those involving web services.

## Code review
- [ ] This pull request has a descriptive title and information useful to a reviewer. There may be a screenshot or screencast attached.
- [ ] I have performed a self-review of my code
- [ ] Issue from task tracker has a link to this pull request

💔 Thank you for submitting a pull request!

2024-10-07 12:14 UTC, saminegash commented on src/sherpa_ai/tools.py
> +                    print("%m" * 70)
remove print

2024-10-07 12:15 UTC, saminegash commented on src/sherpa_ai/tools.py
> +                    print("Scraping failed")
user logger.debug

2024-10-17 12:18 UTC, saminegash requested changes

2024-10-17 12:18 UTC, saminegash commented on src/tests/data/test_link_scraper_action_t_0.jsonl
> +{"input": [{"text": "You are a **question answering assistant** who solves user questions and offers a detailed solution.\\n\\nYour name is QA Agent.\\n\\nContext: what is unique about Ethiopia calen
What is this file is it requered?

2024-10-21 06:45 UTC, Eyobyb commented on src/tests/data/test_link_scraper_action_t_0.jsonl
> +{"input": [{"text": "You are a **question answering assistant** who solves user questions and offers a detailed solution.\\n\\nYour name is QA Agent.\\n\\nContext: what is unique about Ethiopia calen
yes, Its auto generated

2024-10-23 11:39 UTC, saminegash approved these changes

2024-10-24 12:33 UTC, merged